version: '3'

services:
  elando-bot:
    build: ./.
    image: elandos/elando-bot
    ports:
      - 3000:3000
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./public:/app/public
    environment:
      token: ''
      clientId: ''
      clientSecret: ''
      PORT: 3000
      NEW_ACCOUNT_ENDPOINT: ''
      DEBUG: '*'