version: '3'

services:
  elando-bot:
    build: ./.
    image: elandos/elando-bot
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./public:/app/public
    environment:
      token: "${SLACK_TOKEN}"
      clientId: "${SLACK_CLIENT_ID}"
      clientSecret: "${SLACK_CLIENT_SECRET}"
      PORT: 3000
      NEW_ACCOUNT_ENDPOINT: "${NEW_ACCOUNT_ENDPOINT}"
      GET_TRANSACTIONS_ENDPOINT: "${GET_TRANSACTIONS_ENDPOINT}"
      SEND_TRANSACTION_ENDPOINT: "${SEND_TRANSACTION_ENDPOINT}"
      REDIS_HOST: redis
      DEBUG: '*'
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
