export enum CallbackIds {
  SHOW_MENU = "SHOW_MENU",
  CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST",
  SUBMIT_ACCOUNT = "SUBMIT_ACCOUNT",
  SHOW_MENU_FOR_TRANSACTION = "SHOW_MENU_FOR_TRANSACTION",
  SUBMIT_TRANSACTION = "SUBMIT_TRANSACTION",
}